= Examples

[cols="1,1"]
|===
|Input |Output

a|
----
{
 "firstName": "alpha",
 "lastName": "beta"
}
----

a|
----
{
  "firstName" : "Sylvester",
  "lastName" : "Lakin"
}
----

a|
----
{
  "id": "0",
  "username": "string",
  "strings": [
    "traveling",
    "technology"
  ],
  "numbers": [1, 3],
  "nestedObject": {
    "param1": "Mahanaxar",
    "param2": "Valinor"
  },
  "firstName": "blah",
  "lastName": "blahh",
  "gender": "Unknown",
  "address": "123 St"
}
----

a|
----
{
  "id" : "gkXEDuX",
  "username" : "tjkvR",
  "strings" : [ "traveling", "technology", "", "P", "By", "nGHUKAdG" ],
  "numbers" : [ 1, 3, 1873970129, 2146031070, 1655147238 ],
  "nestedObject" : {
    "param1" : "vuSNEWy",
    "param2" : ""
  },
  "firstName" : "Fabian",
  "lastName" : "Bechtelar",
  "gender" : "NonBinary",
  "address" : "47862 Morissette Drive, New Juttaville, MS 09109"
}
----
|===

=== Customization
You may choose to provide a generator specification that informs the library regarding certain aspects of how to generate the Json.

The generator specification is provided as its own node on the input to the library. This looks like an extra node in addition to the original sample to randomize, as the full input to the library.

For an example, see the \___GENERATOR_SPEC node in the input below. The spec helps with overriding the default locale values, as defined in ___LOCALIZATION, and a way to plug in some excel-style formulas for generating specific nodes, as defined in ___FIELDS.

[cols="1,1"]
|===
|Input |Output

a|
----
{
  "___GENERATOR_SPEC": {
    "___LOCALIZATION": {
      "language": "es",
      "country": "MX"
    },
    "___FIELDS": [
      {
        "fieldName": "someStaticField",
        "generatorName": "IDENTITY"
      },
      {
        "fieldName": "id",
        "generatorName": "RANDOM_UUID"
      },
      {
        "fieldName": "someOneOf",
        "generatorName": "ONE_OF",
        "parameters": {
          "values": [
            "B1",
            "B2",
            "AX"
          ]
        }
      }
    ]
  },
  "id": "b66aef25-de3b-4761-8db2-b66793043aac",
  "username": "string",
  "someStaticField": "static",
  "strings": [
    "traveling",
    "technology"
  ],
  "numbers": [1, 3],
  "nestedObject": {
    "param1": "Mahanaxar",
    "param2": "Valinor"
  },
  "firstName": "blah",
  "lastName": "blahh",
  "gender": "Unknown",
  "someOneOf": "B2"
}
----

a|
----
{
  "id" : "6c6b0ab5-be46-4de7-a7a3-6581c10445cd",
  "username" : "CRgksFt",
  "someStaticField" : "static",
  "strings" : [ "traveling", "technology", "ZcSa", "q", "gWC", "eUyAKPUVm", "x", "RzayUr", "Yn" ],
  "numbers" : [ 1, 3, 1037373752, 1550911203, 1972746609, 608209724 ],
  "nestedObject" : {
    "param1" : "Dhu",
    "param2" : "QMtFP"
  },
  "firstName" : "Concepción",
  "lastName" : "Alvarado",
  "gender" : "Polygender",
  "someOneOf" : "B1"
}
----

|===

Run FullSpecTest to see randomized output for an input with all supported fields and spec.

Here is a table showing some additional customized inputs and corresponding results.

[cols="1,1"]
|===
|Input |Output

a|
----
{
  "___GENERATOR_SPEC": {
    "___LOCALIZATION": {
      "language": "fr",
      "country": "FR"
    },
    "___FIELDS": {
      "someStaticField": {
        "type": "IDENTITY"
      },
      "id": {
        "type": "RANDOM_UUID"
      },
      "someOneOf": {
        "type": "ONE_OF",
        "parameters": {
          "values": ["B1", "B2", "AX"]
        }
      }
    }
  },
  "someStaticField": "static",
  "id": "b66aef25-de3b-4761-8db2-b66793043aac",
  "someOneOf": "B2",
  "fullName": "ab",
  "firstName": "a",
  "lastName": "b",
  "gender": "Unknown",
  "address": "123 Bond St, Paris, FR",
  "streetAddress": "123 Bond St",
  "state": "AS",
  "timeZone": "GMT",
  "city": "Paris",
  "creditCardType": "Visa",
  "creditCardNumber": "1234567890123456",
  "creditCardExpiry": "12/31/2022",
  "title": "t",
  "author": "",
  "genre": "Finance",
  "publisher": "RandomHouse",
  "blend": "blend",
  "color": "color",
  "hexColor": "#12",
  "bloodGroup": "A"
}
----

a|
----
{
  "someStaticField" : "static",
  "id" : "c92fd902-ad58-4a41-8b78-785be4620e4a",
  "someOneOf" : "B1",
  "fullName" : "Prof Laura Dufour",
  "firstName" : "Lucie",
  "lastName" : "Girard",
  "gender" : "Polygender",
  "address" : "5 étage, 6 Allée, Voie du Faubourg Saint-Honoré, 71188 Saint-Quentin",
  "streetAddress" : "6461 Boulevard de l'Odéon",
  "state" : "Nord-Pas-de-Calais",
  "timeZone" : "America/Caracas",
  "city" : "Ivry-sur-Seine",
  "creditCardType" : "jcb",
  "creditCardNumber" : "1234-2121-1221-1211",
  "creditCardExpiry" : "2015-11-11",
  "title" : "Le Couloir de tous les mépris",
  "author" : "Henry Romain",
  "genre" : "Mystery",
  "publisher" : "Les Éditions jaune turquoise",
  "blend" : "Express Star",
  "color" : "brun",
  "hexColor" : "#A4E867",
  "bloodGroup" : "A-"
}

----

a|
----
{
  "___GENERATOR_SPEC": {
    "___LOCALIZATION": {
      "language": "fr",
      "country": "CA"
    },
    "___FIELDS": {
      "someStaticField": {
        "type": "IDENTITY"
      },
      "id": {
        "type": "RANDOM_UUID"
      },
      "someOneOf": {
        "type": "ONE_OF",
        "parameters": {
          "values": ["B1", "B2", "AX"]
        }
      }
    }
  },
  "someStaticField": "static",
  "id": "b66aef25-de3b-4761-8db2-b66793043aac",
  "someOneOf": "B2",
  "fullName": "ab",
  "firstName": "a",
  "lastName": "b",
  "gender": "Unknown",
  "address": "123 Bond St, Paris, FR",
  "streetAddress": "123 Bond St",
  "state": "AS",
  "timeZone": "GMT",
  "city": "Paris",
  "creditCardType": "Visa",
  "creditCardNumber": "1234567890123456",
  "creditCardExpiry": "12/31/2022",
  "title": "t",
  "author": "",
  "genre": "Finance",
  "publisher": "RandomHouse",
  "blend": "blend",
  "color": "color",
  "hexColor": "#12",
  "bloodGroup": "A"
}
----

a|
----
{
  "someStaticField" : "static",
  "id" : "36223e50-5c7e-4d57-bdb6-76169d37d9df",
  "someOneOf" : "B1",
  "fullName" : "Mme Louna André",
  "firstName" : "Lisa",
  "lastName" : "Maillard",
  "gender" : "Bigender",
  "address" : "Apt. 522,  d'Orsel 6027, Y7Z3X6 Dijon",
  "streetAddress" : " de l'Odéon 477",
  "state" : "Ontario",
  "timeZone" : "Australia/Melbourne",
  "city" : "Marseille",
  "creditCardType" : "visa",
  "creditCardNumber" : "1211-1221-1234-2201",
  "creditCardExpiry" : "2013-9-12",
  "title" : "L'Odyssée invisible",
  "author" : "Jade Cousin",
  "genre" : "Humor",
  "publisher" : "Au lecteur éclairé",
  "blend" : "Green Symphony",
  "color" : "rose",
  "hexColor" : "#414520",
  "bloodGroup" : "A+"
}

----

a|
----
{
  "___GENERATOR_SPEC": {
    "___LOCALIZATION": {
      "language": "en",
      "country": "US"
    },
    "___FIELDS": {
      "someStaticField": {
        "type": "IDENTITY"
      },
      "id": {
        "type": "RANDOM_UUID"
      },
      "someOneOf": {
        "type": "ONE_OF",
        "parameters": {
          "values": ["B1", "B2", "AX"]
        }
      }
    }
  },
  "someStaticField": "static",
  "id": "b66aef25-de3b-4761-8db2-b66793043aac",
  "someOneOf": "B2",
  "fullName": "ab",
  "firstName": "a",
  "lastName": "b",
  "gender": "Unknown",
  "address": "123 Bond St, Paris, FR",
  "streetAddress": "123 Bond St",
  "state": "AS",
  "timeZone": "GMT",
  "city": "Paris",
  "creditCardType": "Visa",
  "creditCardNumber": "1234567890123456",
  "creditCardExpiry": "12/31/2022",
  "title": "t",
  "author": "",
  "genre": "Finance",
  "publisher": "RandomHouse",
  "blend": "blend",
  "color": "color",
  "hexColor": "#12",
  "bloodGroup": "A"
}
----

a|
----
{
  "someStaticField" : "static",
  "id" : "776706b2-683e-4a37-9028-2db39fdfe714",
  "someOneOf" : "AX",
  "fullName" : "Quiana Upton",
  "firstName" : "Kristopher",
  "lastName" : "Leannon",
  "gender" : "NonBinary",
  "address" : "Suite 035 875 Buddy Underpass, South Lorenton, MN 84834",
  "streetAddress" : "84565 Welch Ford",
  "state" : "Nevada",
  "timeZone" : "America/Mexico_City",
  "city" : "South Wynellside",
  "creditCardType" : "jcb",
  "creditCardNumber" : "1211-1221-1234-2201",
  "creditCardExpiry" : "2011-10-12",
  "title" : "In Dubious Battle",
  "author" : "Arden Wiza",
  "genre" : "Suspense/Thriller",
  "publisher" : "HarperPrism",
  "blend" : "Thanksgiving Blend",
  "color" : "lavender",
  "hexColor" : "#30456D",
  "bloodGroup" : "AB-"
}

----

|===

See the `JsonToJsonGeneratorTest` class for canonical ways to invoke the random Json generator.

This project depends on the `net.datafaker:datafaker` library. That library generates fake json, similar to the javascript `faker.js` library or the python `faker` package.

The default language supported for this library is `en`, and the default region is `US`.

This library can be used in situations where you may want to randomize the data being used across test runs. For example, given a sample, this library can keep generating different data across each run, which can help with better performance test of your system.

NOTE: While the library tries to generate random data, it is possible it can randomly generate some data that is not fake. Exercise caution around its usage.