= Generators

== Custom Generators

This section lists the custom generators provided by the library.

=== IDENTITY

The IDENTITY generator behaves like the mathematical Identity function (see https://en.wikipedia.org/wiki/Identity_function).

For any input x, the generator returns the same value back as the given input value, i.e., `IDENTITY("someValue") = "someValue"`.

[cols="1,1"]
|===
|Input |Output

a|
----
{
  "___GENERATOR_SPEC": {
    "___FIELDS": [
      {
        "fieldName": "someStaticField",
        "generatorName": "IDENTITY"
      }
    ]
  },
  "someStaticField": "someValue"
}
----

a|
----
{
  "someStaticField" : "someValue"
}
----

|===

=== ONE_OF

The ONE_OF generator returns one of a possible set of values.

The item selected is decided based on the size of the array by pseudo-randomly generating an index between 0 and the total number of the possible set of values.

[cols="1,1"]
|===
|Input |Output

a|
----
{
  "___GENERATOR_SPEC": {
    "___FIELDS": [
      {
        "fieldName": "primaryColor",
        "generatorName": "ONE_OF",
        "parameters": {
          "values": [
            "VIOLET",
            "INDIGO",
            "BLUE",
            "GREEN",
            "YELLOW",
            "ORANGE",
            "RED"
          ]
        }
      }
    ]
  },
  "primaryColor": "RED"
}
----

a|
----
{
  "primaryColor" : "ORANGE"
}
----

|===

=== RANDOM_UUID

The RANDOM_UUID generator returns a type 4 pseudo-randomly generated universally unique identifier (UUID).

This generator is automatically applied if your field name/key is `id` or `uuid`.

[cols="1,1"]
|===
|Input |Output

a|
----
{
  "___GENERATOR_SPEC": {
    "___FIELDS": [
      {
        "fieldName": "generatedId",
        "generatorName": "RANDOM_UUID"
      }
    ]
  },
  "generatedId": "1"
}
----

a|
----
{
  "generatedId" : "df4f4d24-a0b9-4488-ba61-44aad6599890"
}
----

|===

== Faker Generators

See link:json-generator/src/main/java/json/generator/faker/FakerType.java[FakerType] in this repository for supported Faker Types.
