= Json Generator
:toc:

== About Json Generator
This is an experimental project to generate random Json strings based on a given input Json string.

`String generate(String input)`

The method generates a random Json based on the input provided. To see some examples, here are some randomly generated Json strings for corresponding inputs.

include::examples.adoc[]

The library takes an opinionated view of what things to randomize and how to go about it.

== Usage

Run FullSpecTest to see randomized output for an input with all supported fields and spec.

See the `JsonToJsonGeneratorTest` class for canonical ways to invoke the random Json generator.

This project depends on the `net.datafaker:datafaker` library. That library generates fake json, similar to the javascript `faker.js` library or the python `faker` package.

The default language supported for this library is `en`, and the default region is `US`.

This library can be used in situations where you may want to randomize the data being used across test runs. For example, given a sample, this library can keep generating different data across each run, which can help with better performance test of your system.

NOTE: While the library tries to generate random data, it is possible it can randomly generate some data that is not fake. Exercise caution around its usage.

== Performance

To evaluate performance, a performance benchmark is provided in the `src/jmh` directory.

To execute the benchmark, run `./gradlew jmh` at the root of this project.

Here is the result of a jmh benchmark execution:

[source:shell]
----
Iteration   1: 24.095 ms/opNG [7m 45s]
Iteration   2: 23.740 ms/opNG [7m 55s]
Iteration   3: 22.989 ms/opNG [8m 5s]
Iteration   4: 23.197 ms/opNG [8m 15s]
Iteration   5: 22.819 ms/opNG [8m 25s]


Result "json.generator.Benchmark.executeMethodToBenchmark":
  28.216 ±(99.9%) 6.692 ms/op [Average]
  (min, avg, max) = (22.819, 28.216, 45.607), stdev = 6.260
  CI (99.9%): [21.524, 34.907] (assumes normal distribution)
.
.
.
Benchmark                           Mode  Cnt   Score   Error  Units
Benchmark.executeMethodToBenchmark  avgt   15  28.216 ± 6.692  ms/op
----